version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis_server:
    image: redis:alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    env_file:
      - .env
    command: sh -c "redis-server --requirepass \"$REDIS_PASSWORD\""
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend_rds:
    build: ./backend_rds
    container_name: backend_rds
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  backend_redis:
    build: ./backend_redis
    container_name: backend_redis
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      redis_server:
        condition: service_healthy

  frontend:
    image: nginx:alpine
    container_name: frontend_nginx
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend_rds
      - backend_redis

volumes:
  pgdata:
